<package format="3">

	<name>tobas_dparam_client</name>
	<version>2.16.4</version>
	<description>Client library for reading and updating distributed Tobas dynamic parameters.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_path_tools</depend>
	<depend>tobas_ros2_tools</depend>
	<depend>tobas_dparam_common</depend>
	<depend>tobas_dparam_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
