// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Tobas, Inc.

#pragma once

#include <map>
#include <string>
#include <vector>

#include <eigen3/Eigen/Geometry>

namespace tobas
{
class LinkModel;
class JointModel;

/* Map of names to instances for JointModel. */
using JointModelMap = std::map<std::string, JointModel*>;

/**
 * @brief A joint from the robot.
 * Models the transform that this joint applies in the kinematic chain.
 */
class JointModel
{
public:
  /* The different types of joints we support. */
  enum JointType
  {
    kUnknown,
    kRevolute,
    kPrismatic,
    kPlanar,
    kFloating,
    kFixed,
  };

  explicit JointModel(const std::string& name, size_t joint_index, size_t first_variable_index);
  virtual ~JointModel();

  /* Get the name of the joint. */
  const std::string& getName() const;

  /* Get the type of joint. */
  JointType getType() const;

  /* Get the link that this joint connects to. */
  const LinkModel* getChildLinkModel() const;

  void setChildLinkModel(const LinkModel* link);

  /* Get the names of the variables that make up this joint, in the order they appear in corresponding states. */
  const std::vector<std::string>& getVariableNames() const;

  /* Get the number of variables that describe this joint. */
  size_t getVariableCount() const;

  /* Get the index of this joint's first variable within the full robot state. */
  size_t getFirstVariableIndex() const;

  /* Get the index of this joint within the robot model. */
  size_t getJointIndex() const;

  /* Provide a default value for the joint given the joint variable bounds. */
  virtual void getVariableDefaultPositions(double* values) const = 0;

  /* Get the joint this one is mimicking. */
  const JointModel* getMimic() const;

  /* If mimicking a joint, this is the offset added to that joint's value. */
  double getMimicOffset() const;

  /* If mimicking a joint, this is the multiplicative factor for that joint's value. */
  double getMimicFactor() const;

  /* Mark this joint as mimicking `mimic` using `factor` and `offset`. */
  void setMimic(const JointModel* mimic, double factor, double offset);

  /* The joint models whose values would be modified if the value of this joint changed. */
  const std::vector<const JointModel*>& getMimicRequests() const;

  /* Notify this joint that there is another joint that mimics it. */
  void addMimicRequest(const JointModel* joint);
  void addDescendantJointModel(const JointModel* joint);
  void addDescendantLinkModel(const LinkModel* link);

  /* Get all the link models that descend from this joint, in the kinematic tree. */
  const std::vector<const LinkModel*>& getDescendantLinkModels() const;

  /* Get all the joint models that descend from this joint, in the kinematic tree. */
  const std::vector<const JointModel*>& getDescendantJointModels() const;

  /* Given the joint values for a joint, compute the corresponding transform. */
  virtual void computeTransform(const double* joint_values, Eigen::Isometry3d& transform) const = 0;

  /* Given the transform generated by joint, compute the corresponding joint values. */
  virtual void computeVariablePositions(const Eigen::Isometry3d& transform, double* joint_values) const = 0;

protected:
  /* The type of joint */
  JointType type_ = kUnknown;

  /* The full names to use for the variables that make up this joint */
  std::vector<std::string> variable_names_;

  /* The link after this joint */
  const LinkModel* child_link_model_ = nullptr;

  /* The joint this one mimics (nullptr for joints that do not mimic) */
  const JointModel* mimic_ = nullptr;

  /* The multiplier to the mimic joint */
  double mimic_factor_ = 1.0;

  /* The offset to the mimic joint */
  double mimic_offset_ = 0.0;

  /* The set of joints that should get a value copied to them when this joint changes */
  std::vector<const JointModel*> mimic_requests_;

  /* Pointers to all the links that will be moved if this joint changes value */
  std::vector<const LinkModel*> descendant_link_models_;

  /* Pointers to all the joints that follow this one in the kinematic tree (including mimic joints) */
  std::vector<const JointModel*> descendant_joint_models_;

private:
  /* Name of the joint */
  const std::string name_;

  /* Index for this joint in the array of joints of the complete model */
  const size_t joint_index_;

  /* The index of this joint's first variable, in the complete robot state */
  const size_t first_variable_index_;
};
}  // namespace tobas
