<package format="3">

	<name>tobas_mission_items</name>
	<version>2.16.2</version>
	<description>C++ mission, mission-item, priority, and altitude-frame data models.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>Apache-2.0</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_std_tools</depend>
	<depend>tobas_yaml_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
