<package format="3">

  <name>tobas_control_system</name>
  <version>2.16.5</version>
  <description>Qt control dashboard for monitoring vehicles and planning and executing missions.</description>
  <maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>magic_enum</depend>
  <depend>qtdeclarative5-dev</depend>
  <depend>qtpositioning5-dev</depend>

  <depend>tobas_path_tools</depend>
  <depend>tobas_ros2_tools</depend>
  <depend>tobas_property_client</depend>
  <depend>tobas_constants</depend>
  <depend>tobas_drone_core</depend>
  <depend>tobas_geographic</depend>
  <depend>tobas_msgs_adapter</depend>
  <depend>tobas_mission_msgs_adapter</depend>
  <depend>tobas_qt_tools</depend>
  <depend>tobas_rqt_bridge</depend>
  <depend>tobas_trajectory_generation</depend>
  <depend>tobas_gui_common</depend>

  <exec_depend>qml-module-qtlocation</exec_depend>
  <exec_depend>qml-module-qtpositioning</exec_depend>
  <exec_depend>qml-module-qtquick-extras</exec_depend>
  <exec_depend>qml-module-qtquick-controls</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
