<package format="3">

	<name>tobas_examples_cpp</name>
	<version>2.16.1</version>
	<description>C++ ROS 2 example nodes and components for Tobas APIs.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_node</depend>
	<depend>tobas_constants</depend>
	<depend>tobas_msgs_adapter</depend>
	<depend>tobas_command_msgs</depend>
	<depend>tobas_mission_items</depend>
	<depend>tobas_mission_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
