<package format="3">

	<name>tobas_tools</name>
	<version>2.16.5</version>
	<description>Temporary package for miscellaneous drone-related tools whose classification is unclear.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_path_tools</depend>
	<depend>tobas_ros2_tools</depend>
	<depend>tobas_constants</depend>
	<depend>tobas_msgs_adapter</depend>
	<depend>tobas_command_msgs_adapter</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
