<package format="3">

	<name>tobas_uadf</name>
	<version>2.16.1</version>
	<description>Parser, data model, and exporter for Tobas UADF airframe descriptions.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_xml_tools</depend>
	<depend>tobas_urdf</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
