<package format="3">

	<name>tobas_tree_server</name>
	<version>2.16.1</version>
	<description>ROS 2 node that publishes and serves the vehicle KDL tree model.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_kdl_parser</depend>
	<depend>tobas_kdl_msgs_adapter</depend>
	<depend>tobas_node</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
