<package format="3">

	<name>tobas_trajectory_generation</name>
	<version>2.16.1</version>
	<description>Online and offline trajectory generators with velocity, acceleration, and jerk constraints.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_math</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
