<package format="3">

	<name>tobas_kdl_msgs_adapter</name>
	<version>2.16.2</version>
	<description>ROS 2 type adapters for KDL-compatible Tobas messages.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_kdl</depend>
	<depend>tobas_kdl_msgs</depend>
	<depend>tobas_eigen_msgs_adapter</depend>
	<depend>tobas_eigen_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
