<package format="3">

  <name>tobas_setup_assistant</name>
  <version>2.16.5</version>
  <description>Qt setup assistant for configuring Tobas projects, vehicles, and runtime environments.</description>
  <maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>magic_enum</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>

  <depend>tobas_inja_vendor</depend>
  <depend>tobas_rapidcsv_vendor</depend>

  <depend>tobas_string_tools</depend>
  <depend>tobas_xml_tools</depend>
  <depend>tobas_git</depend>
  <depend>tobas_kdl_parser</depend>
  <depend>tobas_path_tools</depend>
  <depend>tobas_ros2_tools</depend>
  <depend>tobas_urdf</depend>
  <depend>tobas_property_client</depend>
  <depend>tobas_drone_msgs_adapter</depend>
  <depend>tobas_visualization_msgs</depend>
  <depend>tobas_uadf</depend>
  <depend>tobas_qt_tools</depend>
  <depend>tobas_rviz_wrapper</depend>
  <depend>tobas_gui_common</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>xacro</exec_depend>

  <exec_depend>hardware_interface</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tobas_property_server</exec_depend>
  <exec_depend>tobas_rviz_plugin</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
