<package format="3">

	<name>tobas_fc1xx_ros</name>
	<version>2.16.2</version>
	<description>ROS 2 sensor and actuator driver nodes for FC1xx flight controllers.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_dsp</depend>
	<depend>tobas_ic_drivers</depend>
	<depend>tobas_tools</depend>
	<depend>tobas_msgs_adapter</depend>
	<depend>tobas_drone_msgs_adapter</depend>
	<depend>tobas_real_common</depend>
	<depend>tobas_hardware_common</depend>
	<depend>tobas_fc1xx_core</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
