<package format="3">

	<name>tobas_fc1xx_test</name>
	<version>2.16.1</version>
	<description>Hardware and integration tests for FC1xx flight controllers.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_ic_drivers</depend>
	<depend>tobas_sbus_driver</depend>
	<depend>tobas_fc1xx_core</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
