<?xml version="1.0"?>
<package format="3">

  <name>tobas_inja_vendor</name>
  <version>2.16.4</version>
  <description>Vendor package for the header-only inja template engine</description>
  <maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>nlohmann-json-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
