# cf. /usr/share/doc/hostapd/examples/hostapd.conf

# Interface settings
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

# Interface name to use
interface=ap0

# Driver interface type (hostap/wired/none/nl80211/bsd)
# Default is hostapd
# nl80211 is used with the Linux mac80211 driver
driver=nl80211

# Wi-Fi SSID
ssid={{ ssid }}

# Authentication
auth_algs=1
wpa=2
wpa_passphrase={{ psk }}
wpa_key_mgmt=WPA-PSK
macaddr_acl=0

# CCMP (AES-based) encryption (recommended)
wpa_pairwise=CCMP
rsn_pairwise=CCMP

# Country code
country_code=JP

# Restrict channels and transmit power based on the country code
ieee80211d=1

# DFS support
ieee80211h=1

# Enable Wi-Fi Multimedia (WMM)
# Prioritize traffic to improve quality
wmm_enabled=1

# Fix channel width to the minimum 20 MHz to avoid interference
ht_capab=[HT20]

# 2.4 GHz–specific settings
hw_mode=g
ieee80211n=1
channel=6

# 5 GHz–specific settings
# Use only channels in the W56 band permitted for outdoor use (not allowed for airborne use)
# Limit channel width to 20 or 40 MHz
# hw_mode=a
# ieee80211ac=1
# channel=100
# chanlist=100 104 108 112 116 120 124 128 132 136 140
# vht_oper_chwidth=0
