<package format="3">

  <name>tobas_flight_log_gui</name>
  <version>2.16.1</version>
  <description>Qt application for recording, viewing, and plotting Tobas flight logs.</description>
  <maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>libquazip1-qt5-dev</depend>

  <depend>tobas_string_tools</depend>
  <depend>tobas_kdl</depend>
  <depend>tobas_ros2_tools</depend>
  <depend>tobas_property_client</depend>
  <depend>tobas_msgs</depend>
  <depend>tobas_debug_msgs</depend>
  <depend>tobas_qt_tools</depend>
  <depend>tobas_rqt_bridge</depend>
  <depend>tobas_qwt_wrapper</depend>
  <depend>tobas_gui_common</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
