<package format="3">

	<name>tobas_dynamixel</name>
	<version>2.16.1</version>
	<description>Aggregation package for Dynamixel motor messages, interfaces, and handler nodes.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_dynamixel_handler</exec_depend>
	<exec_depend>tobas_dynamixel_msgs</exec_depend>
	<exec_depend>tobas_dynamixel_ros_interface</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
