<package format="3">

	<name>tobas_linux</name>
	<version>2.16.4</version>
	<description>Linux utilities for devices, processes, files, real-time scheduling, memory locking, and subprocesses.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>libcxxopts-dev</depend>

	<depend>tobas_std_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
