<package format="3">

	<name>tobas_common</name>
	<version>2.16.1</version>
	<description>Aggregation package for reusable Tobas C++ and ROS 2 utility libraries.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_algorithm</exec_depend>
	<exec_depend>tobas_control</exec_depend>
	<exec_depend>tobas_dsp</exec_depend>
	<exec_depend>tobas_eigen_conversions</exec_depend>
	<exec_depend>tobas_eigen_msgs</exec_depend>
	<exec_depend>tobas_eigen_msgs_adapter</exec_depend>
	<exec_depend>tobas_eigen_tools</exec_depend>
	<exec_depend>tobas_geographic</exec_depend>
	<exec_depend>tobas_ic_drivers</exec_depend>
	<exec_depend>tobas_ic_drivers_ros</exec_depend>
	<exec_depend>tobas_kdl</exec_depend>
	<exec_depend>tobas_kdl_conversions</exec_depend>
	<exec_depend>tobas_kdl_msgs</exec_depend>
	<exec_depend>tobas_kdl_msgs_adapter</exec_depend>
	<exec_depend>tobas_linux</exec_depend>
	<exec_depend>tobas_math</exec_depend>
	<exec_depend>tobas_nlp</exec_depend>
	<exec_depend>tobas_path_tools</exec_depend>
	<exec_depend>tobas_quadprog</exec_depend>
	<exec_depend>tobas_ros2_tools</exec_depend>
	<exec_depend>tobas_std_msgs</exec_depend>
	<exec_depend>tobas_std_msgs_adapter</exec_depend>
	<exec_depend>tobas_std_tools</exec_depend>
	<exec_depend>tobas_string_tools</exec_depend>
	<exec_depend>tobas_time_tools</exec_depend>
	<exec_depend>tobas_trajectory_generation</exec_depend>
	<exec_depend>tobas_urdf</exec_depend>
	<exec_depend>tobas_xml_tools</exec_depend>
	<exec_depend>tobas_yaml_tools</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
