<package format="3">

	<name>tobas_code_style</name>
	<version>2.16.2</version>
	<description>Reference package demonstrating the Tobas C++ and CMake coding style.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_cpp_code_style_example</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
