<package format="3">

	<name>tobas_ic_drivers_ros</name>
	<version>2.16.2</version>
	<description>ROS 2 publisher nodes for integrated-circuit sensor drivers.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>geometry_msgs</depend>
  <depend>tobas_ic_drivers</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
