<package format="3">

	<name>tobas_core</name>
	<version>2.16.1</version>
	<description>Aggregation package for the Tobas core flight-control stack.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_camera</exec_depend>
	<exec_depend>tobas_command_msgs</exec_depend>
	<exec_depend>tobas_command_msgs_adapter</exec_depend>
	<exec_depend>tobas_common</exec_depend>
	<exec_depend>tobas_components_rt</exec_depend>
	<exec_depend>tobas_config_servers</exec_depend>
	<exec_depend>tobas_connection_monitor</exec_depend>
	<exec_depend>tobas_constants</exec_depend>
	<exec_depend>tobas_controllers</exec_depend>
	<exec_depend>tobas_cui</exec_depend>
	<exec_depend>tobas_debug_msgs</exec_depend>
	<exec_depend>tobas_debug_msgs_adapter</exec_depend>
	<exec_depend>tobas_debug_tools</exec_depend>
	<exec_depend>tobas_description</exec_depend>
	<exec_depend>tobas_disturbance_observer</exec_depend>
	<exec_depend>tobas_dparam</exec_depend>
	<exec_depend>tobas_drone</exec_depend>
	<exec_depend>tobas_dummy_pkg</exec_depend>
	<exec_depend>tobas_eskf</exec_depend>
	<exec_depend>tobas_failsafe</exec_depend>
	<exec_depend>tobas_fake_publishers</exec_depend>
	<exec_depend>tobas_hardware</exec_depend>
	<exec_depend>tobas_joint_states_bridge</exec_depend>
	<exec_depend>tobas_landing_detection</exec_depend>
	<exec_depend>tobas_manipulation</exec_depend>
	<exec_depend>tobas_mission</exec_depend>
	<exec_depend>tobas_msgs</exec_depend>
	<exec_depend>tobas_msgs_adapter</exec_depend>
	<exec_depend>tobas_node</exec_depend>
	<exec_depend>tobas_object_avoidance</exec_depend>
	<exec_depend>tobas_pose_pid</exec_depend>
	<exec_depend>tobas_property</exec_depend>
	<exec_depend>tobas_rc_teleop</exec_depend>
	<exec_depend>tobas_real</exec_depend>
	<exec_depend>tobas_ros_interface</exec_depend>
	<exec_depend>tobas_rosbag_recorder</exec_depend>
	<exec_depend>tobas_rotor_anomaly_detection</exec_depend>
	<exec_depend>tobas_rotor_controller</exec_depend>
	<exec_depend>tobas_tools</exec_depend>
	<exec_depend>tobas_topic_throttle</exec_depend>
	<exec_depend>tobas_tree_server</exec_depend>
	<exec_depend>tobas_version</exec_depend>
	<exec_depend>tobas_vibration_filter</exec_depend>
	<exec_depend>tobas_wind_model</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
