<package format="3">

	<name>tobas_vibration_filter</name>
	<version>2.16.4</version>
	<description>ROS 2 node that filters IMU vibration and publishes vibration metrics.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_dsp</depend>
	<depend>tobas_node</depend>
	<depend>tobas_msgs_adapter</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
