// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Tobas, Inc.

#include <tobas_constants/imu.hpp>
#include <tobas_constants/ros_interface.hpp>
#include <tobas_dsp/low_pass_filter.hpp>
#include <tobas_gazebo_common/constants.hpp>
#include <tobas_gazebo_conversions/gazebo_kdl.hpp>
#include <tobas_gazebo_conversions/gazebo_ros.hpp>
#include <tobas_gazebo_tools/model_mass_holder.hpp>
#include <tobas_gazebo_tools/utils.hpp>
#include <tobas_math/core.hpp>
#include <tobas_path_tools/join.hpp>
#include <tobas_ros2_tools/time.hpp>
#include <tobas_std_tools/check.hpp>
#include <tobas_std_tools/universal_constants.hpp>
#include <tobas_tools/imu_sampling_time_publisher.hpp>

#include <tobas_gazebo_msgs/msg/engine_state.hpp>
#include <tobas_gazebo_msgs/msg/imu_debug.hpp>
#include <tobas_gazebo_msgs/msg/rotor_state.hpp>
#include <tobas_msgs/srv/configure_imu_low_pass_filter.hpp>
#include <tobas_msgs/srv/configure_imu_rpm_filter.hpp>
#include <tobas_msgs_adapter/imu.hpp>

#include "tobas_gazebo_system_plugins/common/common.hpp"
#include "tobas_gazebo_system_plugins/random.hpp"
#include "tobas_gazebo_system_plugins/rate_manager.hpp"

namespace ch = std::chrono;
namespace cmp = gz::sim::components;

namespace tobas
{
namespace gazebo
{
/**
 * @brief Gazebo IMU plugin
 *
 * - Initial bias is assumed to be calibrated.
 */
class GazeboImuPlugin : public BaseNode,
                        public gz::sim::System,
                        public gz::sim::ISystemConfigure,
                        public gz::sim::ISystemPostUpdate
{
  // Constants
  static constexpr char kDebugTopic[] = "gazebo/imu_debug";

  // TODO: Consider acceleration ratio and gyro vibration more carefully.
  static constexpr double kVibrationAccVerHorRate = 1.0;
  static constexpr double kVibrationAccGyroRate = 0.05;
  static constexpr double kVibrationGyroAttiHeadRate = 0.5;

  using self = GazeboImuPlugin;

public:
  explicit GazeboImuPlugin();

  void Configure(
    const gz::sim::Entity& model,
    const sdf::ElementConstPtr& sdf,
    gz::sim::EntityComponentManager& ecm,
    gz::sim::EventManager&) override;

  void PostUpdate(const gz::sim::UpdateInfo& info, const gz::sim::EntityComponentManager& ecm) override;

private:
  // SDF parameters
  std::string link_name_;
  int update_rate_;             // Update rate [Hz]
  gz::math::Vector3d offset_;   // B_Pos_BS
  double acc_noise_density_;    // Accel noise density [m/s^2/√Hz]
  double acc_random_walk_;      // Accel bias random walk [m/s^2/s/√Hz]
  double acc_bias_corr_time_;   // Accel bias correlation time constant [s]
  double gyro_noise_density_;   // Gyro noise density [rad/s/√Hz]
  double gyro_random_walk_;     // Gyro bias random walk [rad/s/s/√Hz]
  double gyro_bias_corr_time_;  // Gyro bias correlation time constant [s]
  std::vector<std::string> rotor_link_names_;

  const cmp::WorldPose* pose_W_;
  const cmp::LinearAcceleration* acc_B_;
  const cmp::AngularVelocity* gyro_B_;
  const cmp::AngularAcceleration* dgyro_B_;
  const cmp::Gravity* grav_W_;

  RateManager::SharedPtr rate_manager_;
  ModelMassHolder mass_holder_;
  dsp::LowPassFilter<gz::math::Vector3d> acc_lpf_, gyro_lpf_, dgyro_lpf_;
  bool lpf_initialized_ = false;
  bool static_state_detected_ = false;
  gz::math::Vector3d acc_bias_ = gz::math::Vector3d::Zero;
  gz::math::Vector3d gyro_bias_ = gz::math::Vector3d::Zero;
  gz::math::Vector3d prev_gyro_meas_ = gz::math::Vector3d::Zero;
  double engine_vibration_force_;                         // [N] Vibration force generated by the engine
  std::map<std::string, double> rotor_vibration_forces_;  // [N] Vibration force generated by each motor

  std::random_device rnd_dev_;
  NormalDistribution3d normal_;

  ros2::PublisherPtr<tobas_msgs::Imu> imu_raw_pub_;
  ros2::PublisherPtr<tobas_msgs::Imu> imu_filt_pub_;
  ros2::PublisherPtr<tobas_gazebo_msgs::msg::ImuDebug> debug_pub_;
  ImuSamplingTimePublisher sampling_time_pub_;

  ros2::SubscriberPtr<tobas_gazebo_msgs::msg::EngineState> engine_state_sub_;
  std::vector<ros2::SubscriberPtr<tobas_gazebo_msgs::msg::RotorState>> rotor_state_subs_;

  ros2::ServiceServerPtr<tobas_msgs::srv::ConfigureImuLowPassFilter> config_lowpass_filter_ss_;
  ros2::ServiceServerPtr<tobas_msgs::srv::ConfigureImuRpmFilter> config_rpm_filter_ss_;

  void getSdfParams(const sdf::ElementConstPtr& sdf);
  void addNoise(gz::math::Vector3d& acc, gz::math::Vector3d& gyro, const double& dt);

  void engineStateCb(const tobas_gazebo_msgs::msg::EngineState::ConstSharedPtr& msg);

  void configureImuLowPassFilterCb(
    const tobas_msgs::srv::ConfigureImuLowPassFilter::Request::ConstSharedPtr& req,
    const tobas_msgs::srv::ConfigureImuLowPassFilter::Response::SharedPtr& res);
  void configureImuRpmFilter(
    const tobas_msgs::srv::ConfigureImuRpmFilter::Request::ConstSharedPtr& req,
    const tobas_msgs::srv::ConfigureImuRpmFilter::Response::SharedPtr& res);
};

GazeboImuPlugin::GazeboImuPlugin() : normal_(rnd_dev_, 0.0, 1.0)
{
  acc_lpf_.setValue(gz::math::Vector3d::Zero);
  gyro_lpf_.setValue(gz::math::Vector3d::Zero);
  dgyro_lpf_.setValue(gz::math::Vector3d::Zero);
}

void GazeboImuPlugin::Configure(
  const gz::sim::Entity& model,
  const sdf::ElementConstPtr& sdf,
  gz::sim::EntityComponentManager& ecm,
  gz::sim::EventManager&)
{
  initialize("gazebo_imu_plugin", sdf);
  getSdfParams(sdf);

  rate_manager_ = std::make_shared<RateManager>(update_rate_);

  const auto link = ecm.EntityByComponents(cmp::Link(), cmp::ParentEntity(model), cmp::Name(link_name_));
  if (link == gz::sim::kNullEntity) {
    TOBAS_EXIT("Failed to find specified link \"", link_name_, "\".");
  }

  const auto world = ecm.EntityByComponents(cmp::World());
  if (world == gz::sim::kNullEntity) {
    TOBAS_EXIT("Failed to get the world component.");
  }

  TOBAS_CHECK(pose_W_ = getComponent<cmp::WorldPose>(link, ecm));
  TOBAS_CHECK(acc_B_ = getComponent<cmp::LinearAcceleration>(link, ecm));
  TOBAS_CHECK(gyro_B_ = getComponent<cmp::AngularVelocity>(link, ecm));
  TOBAS_CHECK(dgyro_B_ = getComponent<cmp::AngularAcceleration>(link, ecm));
  TOBAS_CHECK(grav_W_ = getComponent<cmp::Gravity>(world, ecm));

  if (!mass_holder_.initialize(model, ecm)) {
    TOBAS_EXIT("Failed to initialize model mass holder.");
  }

  imu_raw_pub_ = createPublisher<tobas_msgs::Imu>(topic::kImuRaw);
  imu_filt_pub_ = createPublisher<tobas_msgs::Imu>(topic::kImuFilt);
  debug_pub_ = createPublisher<tobas_gazebo_msgs::msg::ImuDebug>(kDebugTopic);
  sampling_time_pub_.initialize(node_, node_->now());

  engine_state_sub_ = createSubscriber(kEngineStateGtTopic, &self::engineStateCb, this);

  // Set up motor-state callbacks and subscribers.
  for (const auto& link_name : rotor_link_names_) {
    const auto topic = path::join(kRotorStateGtTopicNS, link_name);
    const ros2::qos::QoS qos(false, false, 1);
    const auto cb = [this, link_name](const tobas_gazebo_msgs::msg::RotorState::ConstSharedPtr& msg)
    { rotor_vibration_forces_[link_name] = msg->vibration_force; };
    const auto sub = node_->create_subscription<tobas_gazebo_msgs::msg::RotorState>(topic, qos, cb);
    rotor_state_subs_.push_back(sub);
  }

  config_lowpass_filter_ss_ = createService<tobas_msgs::srv::ConfigureImuLowPassFilter>(
    service::kConfigureImuLowPassFilter, &self::configureImuLowPassFilterCb, this);
  config_rpm_filter_ss_ = createService<tobas_msgs::srv::ConfigureImuRpmFilter>(
    service::kConfigureImuRpmFilter, &self::configureImuRpmFilter, this);
}

void GazeboImuPlugin::PostUpdate(const gz::sim::UpdateInfo& info, const gz::sim::EntityComponentManager&)
{
  if (rotor_vibration_forces_.size() < rotor_link_names_.size()) {
    if (info.simTime > kCheckTopicWarnStartTime) {
      const auto num_not_received = rotor_link_names_.size() - rotor_vibration_forces_.size();
      TOBAS_WARN_THROTTLE(kWarnPeriod, std::to_string(num_not_received), " rotor states are not received yet.");
    }
  }

  // Get the base-frame state.
  const auto& T_W_B = pose_W_->Data();
  const auto& R_W_B = T_W_B.Rot();
  const auto& acc_B = acc_B_->Data();
  const auto& gyro_B = gyro_B_->Data();
  const auto& dgyro_B = dgyro_B_->Data();

  // Compute the accelerometer reading while considering correction from the offset (memo: 2-26).
  const auto grav_B = R_W_B.RotateVectorReverse(grav_W_->Data());
  const auto acc_corr = gyro_B.Cross(gyro_B.Cross(offset_)) + dgyro_B.Cross(offset_);
  auto acc_meas = acc_B - grav_B + acc_corr;

  // If the offset is translation only, the gyro sensor reading matches the angular velocity of the base frame.
  auto gyro_meas = gyro_B;

  // Get delta time.
  const auto dt = ch::duration<double>(info.dt).count();

  // Add noise to the true values.
  addNoise(acc_meas, gyro_meas, dt);

  // Compute D-gyro.
  const auto dgyro_meas = (gyro_meas - prev_gyro_meas_) / dt;
  prev_gyro_meas_ = gyro_meas;

  // Do not publish until the vehicle position and attitude stabilize to prevent attitude estimation from diverging.
  if (!static_state_detected_) {
    static_state_detected_ = (acc_B.Length() < kStaticAccThresh) && (gyro_B.Length() < kStaticGyroThresh);
    if (static_state_detected_) {
      TOBAS_INFO("Stationary state detected. Start to publish IMU messages.");
      acc_lpf_.setValue(acc_meas);
      gyro_lpf_.setValue(gyro_meas);
      dgyro_lpf_.setValue(dgyro_meas);
    }
    return;
  }

  // Filter.
  if (lpf_initialized_) {
    acc_lpf_.update(acc_meas, dt);
    gyro_lpf_.update(gyro_meas, dt);
    dgyro_lpf_.update(dgyro_meas, dt);
  }

  // Publish rate filter.
  if (!rate_manager_->update(info.simTime)) {
    return;
  }

  // Get current time.
  builtin_interfaces::msg::Time cur_time;
  ros2::timeChronoToMsg(info.simTime, cur_time);

  // Publish raw IMU message.
  auto imu_raw_msg = std::make_unique<tobas_msgs::Imu>();
  imu_raw_msg->header.stamp = cur_time;
  imu_raw_msg->header.frame_id = link_name_;
  vectorGazeboToKDL(acc_meas, imu_raw_msg->accel);
  vectorGazeboToKDL(gyro_meas, imu_raw_msg->gyro);
  vectorGazeboToKDL(dgyro_meas, imu_raw_msg->dgyro);
  imu_raw_pub_->publish(std::move(imu_raw_msg));

  // Publish filtered IMU message.
  if (lpf_initialized_) {
    auto imu_filt_msg = std::make_unique<tobas_msgs::Imu>();
    imu_filt_msg->header.stamp = cur_time;
    imu_filt_msg->header.frame_id = link_name_;
    vectorGazeboToKDL(acc_lpf_.getValue(), imu_filt_msg->accel);
    vectorGazeboToKDL(gyro_lpf_.getValue(), imu_filt_msg->gyro);
    vectorGazeboToKDL(dgyro_lpf_.getValue(), imu_filt_msg->dgyro);
    imu_filt_pub_->publish(std::move(imu_filt_msg));
  }

  // Publish sampling time.
  sampling_time_pub_.publish(cur_time);

  // Publish debug message.
  auto debug_msg = std::make_unique<tobas_gazebo_msgs::msg::ImuDebug>();
  debug_msg->header.stamp = cur_time;
  debug_msg->header.frame_id = link_name_;
  vectorGazeboToRos(acc_bias_, debug_msg->acc_bias);
  vectorGazeboToRos(gyro_bias_, debug_msg->gyro_bias);
  debug_pub_->publish(std::move(debug_msg));
}

void GazeboImuPlugin::getSdfParams(const sdf::ElementConstPtr& sdf)
{
  getSdfParam(sdf, "linkName", link_name_);
  getSdfParam(sdf, "updateRate", update_rate_, kNonNegative);
  getSdfParam(sdf, "offset", offset_);

  getSdfParam(sdf, "accelNoiseDensity", acc_noise_density_, kNonNegative);
  getSdfParam(sdf, "accelRandomWalk", acc_random_walk_, kNonNegative);
  getSdfParam(sdf, "accelBiasCorrelationTime", acc_bias_corr_time_, kPositive);

  getSdfParam(sdf, "gyroNoiseDensity", gyro_noise_density_, kNonNegative);
  getSdfParam(sdf, "gyroRandomWalk", gyro_random_walk_, kNonNegative);
  getSdfParam(sdf, "gyroBiasCorrelationTime", gyro_bias_corr_time_, kPositive);

  getSdfParam(sdf, "rotorLinkNames", rotor_link_names_);
}

void GazeboImuPlugin::addNoise(gz::math::Vector3d& acc, gz::math::Vector3d& gyro, const double& dt)
{
  // Compute vibration force.
  auto vibration_force_sum = engine_vibration_force_;
  for (const auto& [_, vibration_force] : rotor_vibration_forces_) {
    vibration_force_sum += vibration_force;
  }
  const auto vibration_acc_ver = vibration_force_sum / mass_holder_.getMass();        // [m/s^2]
  const auto vibration_acc_hor = vibration_acc_ver * kVibrationAccVerHorRate;         // [m/s^2]
  const auto vibration_gyro_atti = vibration_acc_ver * kVibrationAccGyroRate;         // [rad/s]
  const auto vibration_gyro_head = vibration_gyro_atti * kVibrationGyroAttiHeadRate;  // [rad/s]
  const gz::math::Vector3d vibration_acc(vibration_acc_hor, vibration_acc_hor, vibration_acc_ver);
  const gz::math::Vector3d vibration_gyro(vibration_gyro_atti, vibration_gyro_atti, vibration_gyro_head);

  // Accel
  const auto tau_a = acc_bias_corr_time_;
  // Discrete-time std. dev equivalent to an "integrating" sampler with integration time dt
  const auto sigma_a_d = acc_noise_density_ / std::sqrt(dt);  // [m/s^2]
  const auto sigma_b_a = acc_random_walk_;
  // Compute exact covariance of the process after dt [Maybeck 4-114] (memo: 2-32).
  const auto sigma_b_a_d = sigma_b_a * std::sqrt(tau_a / 2 * (1 - std::exp(-2 * dt / tau_a)));  // [m/s^2]
  // Compute state-transition.
  const auto phi_a_d = std::exp(-dt / tau_a);
  // Simulate accelerometer noise processes and add them to the true linear acceleration.
  acc_bias_ = phi_a_d * acc_bias_ + sigma_b_a_d * normal_.get();
  acc += sigma_a_d * normal_.get() + acc_bias_ + vibration_acc;

  // Gyro
  const auto tau_g = gyro_bias_corr_time_;
  // Discrete-time std. dev equivalent to an "integrating" sampler with integration time dt.
  const auto sigma_g_d = gyro_noise_density_ / std::sqrt(dt);  // [rad/s]
  const auto sigma_b_g = gyro_random_walk_;
  // Compute exact covariance of the process after dt [Maybeck 4-114] (memo: 2-32).
  const auto sigma_b_g_d = sigma_b_g * std::sqrt(tau_g / 2 * (1 - std::exp(-2 * dt / tau_g)));  // [rad/s]
  // Compute state-transition.
  const auto phi_g_d = std::exp(-dt / tau_g);
  // Simulate gyroscope noise processes and add them to the true angular rate.
  gyro_bias_ = phi_g_d * gyro_bias_ + sigma_b_g_d * normal_.get();
  gyro += sigma_g_d * normal_.get() + gyro_bias_ + vibration_gyro;
}

void GazeboImuPlugin::engineStateCb(const tobas_gazebo_msgs::msg::EngineState::ConstSharedPtr& msg)
{
  engine_vibration_force_ = msg->vibration_force;
}

void GazeboImuPlugin::configureImuLowPassFilterCb(
  const tobas_msgs::srv::ConfigureImuLowPassFilter::Request::ConstSharedPtr& req,
  const tobas_msgs::srv::ConfigureImuLowPassFilter::Response::SharedPtr& res)
{
  acc_lpf_.setCutoffFrequency(req->accel_cutoff);
  gyro_lpf_.setCutoffFrequency(req->gyro_cutoff);
  dgyro_lpf_.setCutoffFrequency(req->dgyro_cutoff);

  lpf_initialized_ = true;

  res->success = true;
  res->message.clear();
}

void GazeboImuPlugin::configureImuRpmFilter(
  const tobas_msgs::srv::ConfigureImuRpmFilter::Request::ConstSharedPtr&,
  const tobas_msgs::srv::ConfigureImuRpmFilter::Response::SharedPtr& res)
{
  // TODO: Implement an RPM filter. In discrete time the update frequency is insufficient,
  // so it may be better to create a continuous-time transfer function before signal generation.
  res->success = false;
  res->message = "The RPM filter is not implemented in the simulation.";
}
}  // namespace gazebo
}  // namespace tobas

GZ_ADD_PLUGIN(tobas::gazebo::GazeboImuPlugin, gz::sim::System, gz::sim::ISystemConfigure, gz::sim::ISystemPostUpdate)
