cmake_minimum_required(VERSION 3.25)
project(tobas_ros_interface)

if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type (default Release)" FORCE)
endif()

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic -Wshadow -Wswitch-enum -Werror")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(AMENT_DEPENDENCIES
    std_srvs
    tobas_node
    tobas_tools
    tobas_msgs
    tobas_drone_msgs
    tobas_real_common
    tobas_real_msgs
    tobas_mission_msgs
)

find_package(ament_cmake REQUIRED)

foreach(dependency IN ITEMS ${AMENT_DEPENDENCIES})
  find_package(${dependency} REQUIRED)
endforeach()

file(GLOB_RECURSE NODE_TARGETS CONFIGURE_DEPENDS RELATIVE ${PROJECT_SOURCE_DIR} src/*.cpp)
add_executable(ros_interface ${NODE_TARGETS})
ament_target_dependencies(ros_interface ${AMENT_DEPENDENCIES})

install(TARGETS ros_interface DESTINATION lib/${PROJECT_NAME})

ament_package()
