#!/bin/bash

set -e

# Check username
if [ "$(id -un)" != "pi" ]; then
  echo "This script can only be executed on RPi." >&2
  exit 1
fi

# Set paths
COLCON_WS=~/colcon_ws
RELEASE_DIR=${COLCON_WS}/release
INSTALL_BASE=${RELEASE_DIR}/install
BUILD_BASE=${RELEASE_DIR}/build

# Navigate to the colcon workspace
cd ${COLCON_WS}

# Set log path
export COLCON_LOG_PATH=${RELEASE_DIR}/log

# Limit the number of threads used to build a single package
export MAKEFLAGS="-j1"

# Build
colcon build \
  --merge-install \
  --parallel-workers 1 \
  --install-base ${INSTALL_BASE} \
  --build-base ${BUILD_BASE} \
  --cmake-args \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="-mcpu=native" \
    -DCMAKE_CXX_FLAGS="-mcpu=native" \
  $1 $2 \

echo -e "\033[32mRelease build finished successfully.\033[0m"
