#!/bin/bash

# Check username
if [ "$(id -un)" != "pi" ]; then
  echo "This script can only be executed on RPi." >&2
  exit 1
fi

# Confirm before deleting Tobas settings and data
read -rp "This operation permanently deletes Tobas settings and data. Continue? [y/N] " response
case "$response" in
  [yY] | [yY][eE][sS]) ;;
  *)
    echo "Cleaning canceled."
    exit 0
    ;;
esac

# Clean apt cache
sudo apt clean

# Remove unnecessary files
sudo rm -rf /srv/*
sudo rm -rf /tmp/*
sudo rm -rf /var/backups/*
sudo rm -rf /var/log/*
sudo rm -rf /var/tmp/*
sudo rm -rf /var/lib/apt/lists/*

# Clean the Tobas directory
sudo rm /etc/tobas/config/*
sudo rm -rf /etc/tobas/rosbag/*

# Clean user workspace
cd /etc/tobas/colcon_ws/
sudo colcon clean workspace -y
sudo rm -rf ./src/*

# Clear Wi-Fi client settings
sudo sed -i '4,$ d' /etc/wpa_supplicant/wpa_supplicant-nl80211-wlan0.conf
if [ $? -ne 0 ]; then
  echo "Failed to edit the wpa_supplicant configuration file." >&2
  exit 1
fi

# Clear Wi-Fi hotspot settings
sudo rm /etc/hostapd/hostapd.conf*

# Disable the Tobas services
sudo systemctl disable tobas_real.target

# Reset to the first boot
sudo systemctl enable rpi-resize.service
sudo grep -qw 'resize' /boot/firmware/cmdline.txt || sudo sed -i 's/$/ resize/' /boot/firmware/cmdline.txt
echo uninitialized | sudo tee /etc/machine-id > /dev/null
sudo rm -f /var/lib/dbus/machine-id

echo -e "\033[32mCleaning finished successfully.\033[0m"
