#!/bin/bash

set -e

# Show usage
if [ $# -eq 0 ]; then
  echo "Usage: $(basename "$0") <host>"
  exit 1
fi

# Check username
if [ "$(id -un)" = "pi" ]; then
  echo "This script cannot be executed on RPi." >&2
  exit 1
fi

# Navigate to Tobas root path
cd $(realpath $(dirname "$0"))/../../

# Sync
DEST_DIR="/home/pi/colcon_ws/src/tobas"
rsync -rcmv --delete \
  --rsync-path="mkdir -p ${DEST_DIR} && rsync" \
  tobas tobas_core tobas_dev_tools \
  --exclude-from .gitignore \
  --exclude .git/ \
  --exclude tobas_cui/ \
  --exclude tobas_description/ \
  pi@$1:${DEST_DIR}/
