#!/bin/bash

set -e

PARDIR=$(realpath $(dirname "$0"))

# Stop main service
echo "Stopping Tobas main service."
sudo systemctl stop tobas_real.target
if [ $? -ne 0 ]; then
  echo "Failed to stop tobas_real.target." >&2
  exit 1
fi

# Build Tobas
echo "Building Tobas."
bash ${PARDIR}/tobas_build_release_upto $1
if [ $? -ne 0 ]; then
  echo "Failed to build." >&2
  exit 1
fi

# Install Tobas
echo "Installing Tobas."
bash ${PARDIR}/tobas_install
if [ $? -ne 0 ]; then
  echo "Failed to install." >&2
  exit 1
fi

# Restart main service
echo "Restarting Tobas main service."
sudo systemctl restart tobas_real.target
if [ $? -ne 0 ]; then
  echo "Failed to restart tobas_real.target." >&2
  exit 1
fi

echo -e "\033[32mDeployment finished successfully.\033[0m"
