<package format="3">

	<name>tobas_cyclonedds_config</name>
	<version>2.16.4</version>
	<description>Library for reading, editing, and exporting Cyclone DDS configuration.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_string_tools</depend>
	<depend>tobas_xml_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
