# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tobas, Inc.

# Goal
string local_dir
string remote_dir
bool parents
string[] exclude_dirs
bool superuser

---

# Result
string error_message

---

# Feedback
uint64 total_size
uint64 transferred
