<package format="3">

	<name>tobas_drone_server</name>
	<version>2.16.2</version>
	<description>ROS 2 node that serves the configured Tobas vehicle model.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_node</depend>
	<depend>tobas_msgs</depend>
	<depend>tobas_drone_msgs_adapter</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
