<package format="3">

	<name>tobas_version</name>
	<version>2.16.1</version>
	<description>Compile-time and runtime access to the Tobas software version.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
