<package format="3">

	<name>tobas_real</name>
	<version>2.16.1</version>
	<description>Aggregation package for Tobas real-hardware runtime interfaces.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_dynamixel</exec_depend>
	<exec_depend>tobas_real_common</exec_depend>
	<exec_depend>tobas_real_msgs</exec_depend>
	<exec_depend>tobas_real_ros</exec_depend>
	<exec_depend>tobas_sbus_driver</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
