<package format="3">

	<name>tobas_controllers</name>
	<version>2.16.1</version>
	<description>Aggregation package for Tobas fixed-wing and multicopter flight controllers.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_fixed_wing_controller</exec_depend>
	<exec_depend>tobas_nonplanar_multi_controller</exec_depend>
	<exec_depend>tobas_planar_multi_controller</exec_depend>
	<exec_depend>tobas_random_axis_tilt_multi_controller</exec_depend>
	<exec_depend>tobas_y_axis_tilt_multi_controller</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
