<package format="3">

	<name>tobas_failsafe</name>
	<version>2.16.5</version>
	<description>Vehicle health monitoring and failsafe execution nodes.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_dsp</depend>
	<depend>tobas_node</depend>
	<depend>tobas_tools</depend>
	<depend>tobas_msgs_adapter</depend>
	<depend>tobas_drone_msgs_adapter</depend>
	<depend>tobas_mission_items</depend>
	<depend>tobas_mission_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
