<package format="3">

	<name>tobas_control</name>
	<version>2.16.4</version>
	<description>Control-system algorithms including state-space models, optimal control, Kalman filtering, MPC, and PID.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_quadprog</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
