<package format="3">

	<name>tobas_ssh_client</name>
	<version>2.16.4</version>
	<description>C++ ROS 2 client for remote command execution and file transfer over SSH.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_ros2_tools</depend>
	<depend>tobas_ssh_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
