<package format="3">

	<name>tobas_pose_pid</name>
	<version>2.16.4</version>
	<description>Position and orientation PID-family controllers for vehicle pose control.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_kdl</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
