#!/bin/bash

# Reload system daemons
sudo systemctl daemon-reload

# Apply udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger

# Enable "wait" service to make sure that services start after the network is up
# https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
sudo systemctl enable systemd-networkd-wait-online.service

# Enable SSH server
sudo systemctl enable ssh.service

# Enable services for using RPi as an access point
# https://www.mikan-tech.net/entry/raspi-wifi-ap-sta
sudo systemctl unmask hostapd.service
sudo systemctl enable hostapd.service

# Setting up a routed wireless access point
# https://www.mikan-tech.net/entry/raspi-ap-sta-router
sudo iptables -t nat -A POSTROUTING -s 192.168.249.0/24 ! -d 192.168.249.0/24 -j MASQUERADE
sudo netfilter-persistent save

# Use WPA Supplicant instead of NetworkManager
sudo systemctl disable NetworkManager.service
sudo systemctl enable wpa_supplicant-nl80211@wlan0.service

# Enable Tobas services
sudo systemctl enable tobas_network_wait_online.service
