<package format="3">

	<name>tobas_drone</name>
	<version>2.16.1</version>
	<description>Aggregation package for Tobas vehicle models, interfaces, and analysis tools.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_drone_core</exec_depend>
	<exec_depend>tobas_drone_msgs</exec_depend>
	<exec_depend>tobas_drone_msgs_adapter</exec_depend>
	<exec_depend>tobas_drone_server</exec_depend>
	<exec_depend>tobas_drone_tools</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
