// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Tobas, Inc.

#pragma once

#include "./tree_id_solver_rne.hpp"

namespace tobas
{
namespace kdl
{
/**
 * @brief Tree version of `kdl::ChainDynParam`.
 */
class TreeDynParam : public TreeSolverI
{
  using super = TreeSolverI;

public:
  explicit TreeDynParam(const Tree& tree, const Vector& grav = Vector(0.0, 0.0, -st::kGravity));

  bool updateInternalDataStructures() override;

  /**
   * @brief Compute the torque generated by Coriolis force.
   *
   * @param q Joint angles.
   * @param qd Joint angular velocities.
   */
  int jntToCoriolis(const JntArray& q, const JntArray& qd);

  /**
   * @brief Compute the torque generated by gravity.
   *
   * @param q Joint angles.
   */
  int jntToGravity(const JntArray& q);

  inline const JntArray& getCoriolisEffort() const;
  inline const JntArray& getGravityEffort() const;

private:
  TreeIdSolver_RNE rne_coriolis_;
  TreeIdSolver_RNE rne_gravity_;

  JntArray jntarray_null_;

  void resize();
};

inline const JntArray& TreeDynParam::getCoriolisEffort() const
{
  return rne_coriolis_.getEfforts();
}

inline const JntArray& TreeDynParam::getGravityEffort() const
{
  return rne_gravity_.getEfforts();
}
}  // namespace kdl
}  // namespace tobas
