# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tobas, Inc.

# Lift force
float64 c_lift_0
float64 c_lift_alpha

# Drag force
float64 c_drag_0
float64 c_drag_alpha

# Side force
float64 c_side_beta

# Roll moment
float64 c_roll_beta
float64 c_roll_p
float64 c_roll_r

# Pitch moment
float64 c_pitch_0
float64 c_pitch_alpha
float64 c_pitch_abs_beta
float64 c_pitch_alpha_rate
float64 c_pitch_q

# Yaw moment
float64 c_yaw_beta
float64 c_yaw_p
float64 c_yaw_r
