<package format="3">

	<name>tobas_ros2_tools</name>
	<version>2.16.2</version>
	<description>Reusable ROS 2 utilities for nodes, QoS, timing, actions, services, parameters, TF, and rosbag.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>rclcpp</depend>
	<depend>tf2_ros</depend>
	<depend>rosbag2_cpp</depend>

	<exec_depend>ros2launch</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
