<package format="3">

	<name>tobas_rotor_controller</name>
	<version>2.16.1</version>
	<description>ROS 2 node that converts rotor thrust commands into actuator setpoints.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>std_srvs</depend>
	<depend>tobas_node</depend>
	<depend>tobas_msgs_adapter</depend>
	<depend>tobas_drone_msgs_adapter</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
