<package format="3">

	<name>tobas_std_tools</name>
	<version>2.16.2</version>
	<description>Library containing basic functionality comparable to extensions of the standard library.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<build_depend>eigen</build_depend>

	<depend>tobas_math</depend>
	<depend>tobas_algorithm</depend>
	<depend>tobas_time_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
