# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tobas, Inc.

string name

# The maximum size a bagfile can be, in bytes, before it is split.
# A value of 0 indicates that bagfile splitting will not be used.
uint64 max_file_size

# The cache size indicates how many messages can maximally be hold in cache before these being written to disk.
# A value of 0 disables caching and every write happens directly to disk.
uint64 max_cache_size

bool overwrite

---

bool success
string message
