# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tobas, Inc.

uint16 quality_factor   # [-]
uint16 min_center_freq  # [Hz]
uint16 fade_range       # [Hz]
uint16 lpf_cutoff       # [Hz]
---
bool success
string message
