<package format="3">

	<name>tobas_colcon_cpp</name>
	<version>2.16.5</version>
	<description>C++ interface for invoking colcon builds and processing build events.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_linux</depend>
	<depend>tobas_ros2_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
