<package format="3">

	<name>tobas_drone_core</name>
	<version>2.16.2</version>
	<description>Defines the drone structure. Defines only the minimum required information.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_nlp</depend>
	<depend>tobas_kdl</depend>
	<depend>tobas_yaml_tools</depend>
	<depend>tobas_constants</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
