<package format="3">

	<name>tobas_property</name>
	<version>2.16.2</version>
	<description>Aggregation package for the Tobas distributed property service.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_property_client</exec_depend>
	<exec_depend>tobas_property_common</exec_depend>
	<exec_depend>tobas_property_msgs</exec_depend>
	<exec_depend>tobas_property_server</exec_depend>
	<exec_depend>tobas_property_tree</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
