<package format="3">

	<name>tobas_joint_states_bridge</name>
	<version>2.16.4</version>
	<description>ROS 2 node that bridges Tobas joint states to standard joint-state interfaces.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>sensor_msgs</depend>
	<depend>tobas_node</depend>
	<depend>tobas_constants</depend>
	<depend>tobas_msgs_adapter</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
