<package format="3">

	<name>tobas_ssh</name>
	<version>2.16.5</version>
	<description>Aggregation package for Tobas SSH clients, servers, authentication keys, and ROS 2 interfaces.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_ssh_authkey</exec_depend>
	<exec_depend>tobas_ssh_client</exec_depend>
	<exec_depend>tobas_ssh_msgs</exec_depend>
	<exec_depend>tobas_ssh_server</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
