<package format="3">

	<name>tobas_dsp</name>
	<version>2.16.1</version>
	<description>Digital signal-processing filters and online statistical estimators for Tobas.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_std_tools</depend>
	<depend>tobas_eigen_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
