<package format="3">

	<name>tobas_fc2xx</name>
	<version>2.16.2</version>
	<description>Aggregation package for Tobas FC2xx flight-controller hardware support.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<exec_depend>tobas_fc2xx_core</exec_depend>
	<exec_depend>tobas_fc2xx_ros</exec_depend>
	<exec_depend>tobas_fc2xx_test</exec_depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
