<package format="3">

	<name>tobas_crypt</name>
	<version>2.16.4</version>
	<description>Cryptographic hashing and password-verification utilities for Tobas applications.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>
	<buildtool_depend>pkg-config</buildtool_depend>

	<depend>tobas_linux</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
