<package format="3">

	<name>tobas_wind_model</name>
	<version>2.16.4</version>
	<description>Dryden turbulence and wind-disturbance model library.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_std_tools</depend>
	<depend>tobas_constants</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
