<package format="3">

	<name>tobas_fc1xx_core</name>
	<version>2.16.4</version>
	<description>Low-level PWM, DShot, and battery drivers for FC1xx hardware.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>tobas_linux</depend>
	<depend>tobas_std_tools</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
