<package format="3">

  <name>tobas_rviz_plugin</name>
  <version>2.16.1</version>
  <description>RViz display plugins for visualizing Tobas vehicles, models, trajectories, and sensor data.</description>
  <maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>tf2_eigen</depend>
  <depend>rsl</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>tobas_visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rviz plugin="${prefix}/rviz_plugin_description.xml"/>
  </export>

</package>
