<package format="3">

	<name>tobas_real_ros</name>
	<version>2.16.2</version>
	<description>ROS 2 handlers for real IMU, magnetometer, RC, joint, CPU, and propulsion-system data.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>magic_enum</depend>
	<depend>sensor_msgs</depend>

	<depend>tobas_string_tools</depend>
	<depend>tobas_dsp</depend>
	<depend>tobas_linux</depend>
	<depend>tobas_property_tree</depend>
	<depend>tobas_node</depend>
	<depend>tobas_tools</depend>
	<depend>tobas_msgs_adapter</depend>
	<depend>tobas_drone_msgs_adapter</depend>
	<depend>tobas_real_common</depend>
	<depend>tobas_real_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
