<package format="3">

	<name>tobas_components_rt</name>
	<version>2.16.1</version>
	<description>Real-time-oriented ROS 2 component managers, executors, and timer-coalescing containers.</description>
	<maintainer email="m.dohi@tobas.jp">Masayoshi Dohi</maintainer>
	<license>GPL-3.0-or-later</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>rclcpp</depend>
	<depend>rclcpp_components</depend>
	<depend>tobas_linux</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>

</package>
