# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tobas, Inc.

# This message contains information about the robot state, i.e. the positions of its joints and links.
sensor_msgs/JointState joint_state

# Joints that may have multiple DOF are specified here.
sensor_msgs/MultiDOFJointState multi_dof_joint_state

# Flag indicating whether this scene is to be interpreted as a diff with respect to some other scene.
# This is mostly important for handling the attached bodies
# (whether or not to clear the attached bodies of a tobas::RobotState before updating it with this message).
bool is_diff
